import React, { useRef, useState } from "react";
import { copyText, define, mark, useControllable, type CommonProps, type Tone } from "../../../core/base";
import { SvgAsset } from "../../../core/artwork";
import { useDecoration } from "../../../core/motion/hooks";
import { ArtworkFrame } from "../../layout/ArtworkFrame/ArtworkFrame";
import { Avatar } from "../../layout/Avatar/Avatar";
import { ButtonGroup } from "../../layout/ButtonGroup/ButtonGroup";
import { Card } from "../../layout/Card/Card";
import { Icon } from "../../layout/Icon/Icon";
import { IconTile } from "../../layout/IconTile/IconTile";
import { SectionHeader } from "../../layout/SectionHeader/SectionHeader";
import { Text } from "../../layout/Text/Text";
import { illustrations } from "../../layout/shared";
import { Button } from "../../controls/Button/Button";
import { Field } from "../../controls/Field/Field";
import { FilePicker } from "../../controls/FilePicker/FilePicker";
import { IconButton } from "../../controls/IconButton/IconButton";
import { Tabs } from "../../controls/Tabs/Tabs";
import { TextField } from "../../controls/TextField/TextField";
import { ToggleButton } from "../../controls/ToggleButton/ToggleButton";
import { Badge } from "../../feedback/Badge/Badge";
import { Dialog } from "../../feedback/Dialog/Dialog";
import { KeyValueList } from "../../feedback/KeyValueList/KeyValueList";
import { Menu } from "../../feedback/Menu/Menu";
import { MetricCard } from "../../feedback/MetricCard/MetricCard";
import { ProgressBar } from "../../feedback/ProgressBar/ProgressBar";
import { StatusIndicator } from "../../feedback/StatusIndicator/StatusIndicator";
import { Steps } from "../../feedback/Steps/Steps";
import { Toast } from "../../feedback/Toast/Toast";
import { type MenuItemData } from "../../feedback/shared";
import { AudioPlayer } from "../../media/AudioPlayer/AudioPlayer";
import { LevelMeter } from "../../media/LevelMeter/LevelMeter";
import { RotaryKnob } from "../../media/RotaryKnob/RotaryKnob";
import { VolumeControl } from "../../media/VolumeControl/VolumeControl";
import { type RoleEmblemProps, type RecordingCardProps, type ProcessingTaskCardProps, type ParticipantCardProps, type ProfileCardProps, type ThemeName, type ThemePickerProps, type RoomConnection, type RoomConnectionFormProps, type ModelStatusCardProps, type StorageSummaryProps, type DiagnosticsPanelProps, type PerformanceSummaryProps } from "../shared";
import { RoleEmblem } from "../RoleEmblem/RoleEmblem";
import { RecordingCard } from "../RecordingCard/RecordingCard";
import { ProcessingTaskCard } from "../ProcessingTaskCard/ProcessingTaskCard";
import { ParticipantCard } from "../ParticipantCard/ParticipantCard";
import { ProfileCard } from "../ProfileCard/ProfileCard";
import { ThemePicker } from "../ThemePicker/ThemePicker";
import { RoomConnectionForm } from "../RoomConnectionForm/RoomConnectionForm";
import { ModelStatusCard } from "../ModelStatusCard/ModelStatusCard";
import { StorageSummary } from "../StorageSummary/StorageSummary";
import { DiagnosticsPanel } from "../DiagnosticsPanel/DiagnosticsPanel";

export const PerformanceSummary = define<PerformanceSummaryProps>("PerformanceSummary", p => <div {...mark("PerformanceSummary", p)}><div className="ad-metric-grid"><MetricCard value={p.pitch ?? 49} title="Высота" /><MetricCard value={p.rhythm ?? 0} title="Ритм" icon="wave" description="Точность начала нот" /><MetricCard value={p.stability ?? 0} title="Стабильность" icon="clock" description="Удержание высоты" /></div><Card title="Нужно потренироваться"><div className="ad-summary-score"><strong>{p.score ?? 16}</strong><span>общая оценка</span></div><p>{p.advice ?? "Потренируйте вступления: слушайте сильную долю и начинайте точно на ней."}</p></Card></div>);
