import React, { createElement, useRef } from "react";
import type { ElementType, ReactNode } from "react";
import { define, mark, type CommonProps, type VectorNode } from "../../../core/base";
import { SvgAsset } from "../../../core/artwork";
import { useBorder } from "../../../core/motion/hooks";
import iconData from "../../../artwork/icons.json";
import artworkData from "../../../artwork/illustrations.json";
import { icons, illustrations, HeaderView, part, type IconName, type IconProps, type TextProps, type SurfaceProps, type HeaderProps, type CardProps, type IconTileProps, type AvatarProps, type TabPanelProps, type ScrollAreaProps, type DividerProps, type IllustrationProps } from "../shared";
import { Icon } from "../Icon/Icon";
import { Text } from "../Text/Text";
import { Surface } from "../Surface/Surface";
import { PageHeader } from "../PageHeader/PageHeader";
import { SectionHeader } from "../SectionHeader/SectionHeader";
import { Card } from "../Card/Card";
import { IconTile } from "../IconTile/IconTile";
import { Avatar } from "../Avatar/Avatar";
import { DialogHeader } from "../DialogHeader/DialogHeader";
import { DialogBody } from "../DialogBody/DialogBody";
import { DialogActions } from "../DialogActions/DialogActions";
import { Toolbar } from "../Toolbar/Toolbar";
import { ButtonGroup } from "../ButtonGroup/ButtonGroup";
import { ScrollArea } from "../ScrollArea/ScrollArea";
import { Divider } from "../Divider/Divider";
import { SceneIllustration } from "../SceneIllustration/SceneIllustration";
import { ArtworkFrame } from "../ArtworkFrame/ArtworkFrame";
import { BrandMark } from "../BrandMark/BrandMark";

export const TabPanel = define<TabPanelProps>("TabPanel", p => <div {...mark("TabPanel", p)} role="tabpanel" aria-labelledby={p.labelledBy} hidden={p.hidden} tabIndex={0}>{p.children}</div>);
