import React, { createElement, useRef } from "react";
import type { ElementType, ReactNode } from "react";
import { define, mark, type CommonProps, type VectorNode } from "../../../core/base";
import { SvgAsset } from "../../../core/artwork";
import { useBorder } from "../../../core/motion";
import iconData from "../../../artwork/icons.json";
import artworkData from "../../../artwork/illustrations.json";
import { icons, illustrations, HeaderView, part, type IconName, type IconProps, type TextProps, type SurfaceProps, type HeaderProps, type CardProps, type IconTileProps, type AvatarProps, type TabPanelProps, type ScrollAreaProps, type DividerProps, type IllustrationProps } from "../_shared";
import { Icon } from "../Icon";
import { Text } from "../Text";
import { Surface } from "../Surface";
import { PageHeader } from "../PageHeader";
import { SectionHeader } from "../SectionHeader";
import { Card } from "../Card";
import { IconTile } from "../IconTile";
import { Avatar } from "../Avatar";
import { DialogHeader } from "../DialogHeader";
import { DialogBody } from "../DialogBody";
import { DialogActions } from "../DialogActions";
import { Toolbar } from "../Toolbar";
import { ButtonGroup } from "../ButtonGroup";
import { TabPanel } from "../TabPanel";
import { Divider } from "../Divider";
import { SceneIllustration } from "../SceneIllustration";
import { ArtworkFrame } from "../ArtworkFrame";
import { BrandMark } from "../BrandMark";

export const ScrollArea = define<ScrollAreaProps>("ScrollArea", p => <div {...mark("ScrollArea", p)} tabIndex={0} aria-label={p.label} style={{ maxHeight: p.height ?? 180, ...p.style }}>{p.children}</div>);
