import React, { useRef, useState } from "react";
import { copyText, define, mark, useControllable, type CommonProps, type Tone } from "../../../core/base";
import { SvgAsset } from "../../../core/artwork";
import { useDecoration } from "../../../core/motion/hooks";
import { ArtworkFrame } from "../../layout/ArtworkFrame/ArtworkFrame";
import { Avatar } from "../../layout/Avatar/Avatar";
import { ButtonGroup } from "../../layout/ButtonGroup/ButtonGroup";
import { Card } from "../../layout/Card/Card";
import { Icon } from "../../layout/Icon/Icon";
import { IconTile } from "../../layout/IconTile/IconTile";
import { SectionHeader } from "../../layout/SectionHeader/SectionHeader";
import { Text } from "../../layout/Text/Text";
import { illustrations } from "../../layout/shared";
import { Button } from "../../controls/Button/Button";
import { Field } from "../../controls/Field/Field";
import { FilePicker } from "../../controls/FilePicker/FilePicker";
import { IconButton } from "../../controls/IconButton/IconButton";
import { Tabs } from "../../controls/Tabs/Tabs";
import { TextField } from "../../controls/TextField/TextField";
import { ToggleButton } from "../../controls/ToggleButton/ToggleButton";
import { Badge } from "../../feedback/Badge/Badge";
import { Dialog } from "../../feedback/Dialog/Dialog";
import { KeyValueList } from "../../feedback/KeyValueList/KeyValueList";
import { Menu } from "../../feedback/Menu/Menu";
import { MetricCard } from "../../feedback/MetricCard/MetricCard";
import { ProgressBar } from "../../feedback/ProgressBar/ProgressBar";
import { StatusIndicator } from "../../feedback/StatusIndicator/StatusIndicator";
import { Steps } from "../../feedback/Steps/Steps";
import { Toast } from "../../feedback/Toast/Toast";
import { type MenuItemData } from "../../feedback/shared";
import { AudioPlayer } from "../../media/AudioPlayer/AudioPlayer";
import { LevelMeter } from "../../media/LevelMeter/LevelMeter";
import { RotaryKnob } from "../../media/RotaryKnob/RotaryKnob";
import { VolumeControl } from "../../media/VolumeControl/VolumeControl";
import { type RoleEmblemProps, type RecordingCardProps, type ProcessingTaskCardProps, type ParticipantCardProps, type ProfileCardProps, type ThemeName, type ThemePickerProps, type RoomConnection, type RoomConnectionFormProps, type ModelStatusCardProps, type StorageSummaryProps, type DiagnosticsPanelProps, type PerformanceSummaryProps } from "../shared";
import { RoleEmblem } from "../RoleEmblem/RoleEmblem";
import { RecordingCard } from "../RecordingCard/RecordingCard";
import { ProcessingTaskCard } from "../ProcessingTaskCard/ProcessingTaskCard";
import { ParticipantCard } from "../ParticipantCard/ParticipantCard";
import { ProfileCard } from "../ProfileCard/ProfileCard";
import { RoomConnectionForm } from "../RoomConnectionForm/RoomConnectionForm";
import { ModelStatusCard } from "../ModelStatusCard/ModelStatusCard";
import { StorageSummary } from "../StorageSummary/StorageSummary";
import { DiagnosticsPanel } from "../DiagnosticsPanel/DiagnosticsPanel";
import { PerformanceSummary } from "../PerformanceSummary/PerformanceSummary";

export const ThemePicker = define<ThemePickerProps>("ThemePicker", p => {
  const [value, setValue] = useControllable(p.value, p.defaultValue ?? "ruby", p.onValueChange);
  const themes: Array<[ThemeName, string, string]> = [["ruby", "Тёмная", "#ff244c"], ["light", "Светлая", "#ecc794"], ["green", "Зелёная", "#10deae"], ["violet", "Фиолетовая", "#b680ff"]];
  return <div {...mark("ThemePicker", p)} aria-label="Тема">{themes.map(([key, name, color]) => <Button key={key} aria-pressed={key === value} onClick={() => setValue(key)}><span style={{ background: `radial-gradient(ellipse at 50% 100%, ${color}, #09070c 80%)` }}><Icon name="music" size={32} /></span><strong>{name}</strong></Button>)}</div>;
});
